# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 228358ddfa09012d09210eeca7685241560d5f3258902163d804f5b8fd0faf5f3bfb89f0fa2d929adfcee266b766e27948594dc6d3319041c4ee9dd4d2a23220

test:
  secret_key_base: 05ce7a303c7d5eb25ef0d4d984783dc82f91b024626646dba882e1bdf1b8ace3765c153b87202c6482b49547e0d2673320348017a0d5738636b6713d2892ecc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
